[project]
name = "skeit"
version = "0.1.0"
description = "Collection of tools/scripts"
requires-python = ">=3.10"
dependencies = ["rich"]

[project.scripts]
skeit = "skeit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
